'''
name: Code Quality and Tests
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          '''
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort
          
      - name: Check Black formatting
        run: black . --check
        run: black .
        
      - name: Check Import sorting
        run: isort . --check-only --diff
'''
## Add this once we have pytests to run  
#  tests:
#    needs: code-quality
#    runs-on: ubuntu-latest  # Changed to only run on Ubuntu
#    steps:
#      - uses: actions/checkout@v4
#      
#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: '3.10'

#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          # Install all requirements except pywin32
#          pip install $(grep -v "pywin32" requirements.txt)
#          pip install pytest

#      - name: Run tests
#       run: pytest


name: Code Quality and Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python3.10 -m pip install --upgrade pip
          python3.10 -m pip install black isort

      - name: Check Black formatting
        run: |
          python3.10 -m black . --check
          if [ $? -ne 0 ]; then
            echo "Black formatting check failed!"
            exit 1
          fi

      - name: Check Import sorting
        run: |
          python3.10 -m isort . --check-only --diff
          if [ $? -ne 0 ]; then
            echo "isort check failed!"
            exit 1
            fi
            
